apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/instance: parca-ui
    app.kubernetes.io/name: parca-ui
    app.kubernetes.io/version: dev
  name: parca-ui
  namespace: parca
