---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: observability
    app.kubernetes.io/instance: parca
    app.kubernetes.io/name: parca
    app.kubernetes.io/version: v0.0.3-alpha
  name: parca
  namespace: parca
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: observability
      app.kubernetes.io/instance: parca
      app.kubernetes.io/name: parca
  template:
    metadata:
      labels:
        app.kubernetes.io/component: observability
        app.kubernetes.io/instance: parca
        app.kubernetes.io/name: parca
        app.kubernetes.io/version: v0.0.3-alpha
    spec:
      containers:
      - args:
        - /parca
        - --config-path=/parca.yaml
        - --log-level=debug
        - --cors-allowed-origins=*
        image: ghcr.io/parca-dev/parca:v0.0.3-alpha-11-g1f5b17c
        livenessProbe:
          exec:
            command:
            - /grpc-health-probe
            - -v
            - -addr=:7070
          initialDelaySeconds: 5
        name: parca
        ports:
        - containerPort: 7070
          name: all
        readinessProbe:
          exec:
            command:
            - /grpc-health-probe
            - -v
            - -addr=:7070
          initialDelaySeconds: 10
        resources: {}
        terminationMessagePolicy: FallbackToLogsOnError
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
      serviceAccountName: parca
      terminationGracePeriodSeconds: 120
---
apiVersion: v1
kind: Namespace
metadata:
  name: parca
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: observability
    app.kubernetes.io/instance: parca
    app.kubernetes.io/name: parca
    app.kubernetes.io/version: v0.0.3-alpha
  name: parca
  namespace: parca
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: observability
    app.kubernetes.io/instance: parca
    app.kubernetes.io/name: parca
    app.kubernetes.io/version: v0.0.3-alpha
  name: parca
  namespace: parca
spec:
  ports:
  - name: all
    port: 7070
    targetPort: 7070
  selector:
    app.kubernetes.io/component: observability
    app.kubernetes.io/instance: parca
    app.kubernetes.io/name: parca
