apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: observability
    app.kubernetes.io/instance: parca
    app.kubernetes.io/name: parca
    app.kubernetes.io/version: dev
  name: parca
  namespace: parca
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: observability
      app.kubernetes.io/instance: parca
      app.kubernetes.io/name: parca
  template:
    metadata:
      labels:
        app.kubernetes.io/component: observability
        app.kubernetes.io/instance: parca
        app.kubernetes.io/name: parca
        app.kubernetes.io/version: dev
    spec:
      containers:
      - args:
        - /parca
        - --config-path=/parca.yaml
        - --log-level=debug
        - --cors-allowed-origins=*
        - --debug-infod-upstream-servers=https://debuginfod.elfutils.org
        - --debug-infod-http-request-timeout=5m
        image: parca.io/parca/parca:dev
        livenessProbe: null
        name: parca
        ports:
        - containerPort: 7070
          name: http
        readinessProbe: null
        resources: {}
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/parca
          name: parca-config
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
      serviceAccountName: parca
      terminationGracePeriodSeconds: 120
      volumes:
      - configMap:
          name: parca-config
        name: parca-config
