name: Documents

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - .github/workflows/docs.yml
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - .github/workflows/docs.yml

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true

      - name: Docs check
        run: |
          make README.md
          git diff --exit-code ':!deploy'
