name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  goreleaser:
    name: Goreleaer Dry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install llvm
        run: sudo apt-get install llvm

      - name: Build UI
        run: make ui

      - name: Dry Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --skip-validate --skip-publish

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install llvm
        run: sudo apt-get install llvm

      - name: Build
        run: make build

      - name: Format
        run: make format

      - name: Test
        run: make go/test
