name: Protobuf

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://parca:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Set up environment
        run: ./env-proto.sh

      - name: Lint
        run: make proto/lint

      - name: Generate
        run: make proto/generate && git diff --exit-code
